services:
  - type: web
    name: geolead
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fop_search_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.5
      - key: LANDID_USERNAME
        value: aaron@fulleroak.com
      - key: LANDID_PASSWORD
        value: cU2Vj1GNGEklgdSN