services:
  - type: web
    name: geolead
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fop_search_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.5